### ISSUE TITLE
hyper-parameters during training  SemanticKITTI ?

### ISSUE THREAD

**Issue by tornadomeet** [QingyongHu/RandLA-Net#1]
hello @QingyongHu 

what the value of ```batch-size``` and ```N``` when training  SemanticKITTI ?

in the ```3.4. Implementation``` of your paper, it said used the fixed ```N ~= 1e6```, but the number point of each scan of SemanticKITTI is less than 1e-6;

another, how the training ```N``` value influence the test performance? for example there is 2 training config,
a. use ```N=1e-4``` during training
b. use ```N=1e-5``` during training

which config will get best performance on SemanticKITTI?

thanks!

**Comment by Yang7879** [comment]
Hi @tornadomeet, thanks for your interest in our work and pointing out the inconsistency. We double-checked the code and confirm that we use ~10^5 pts for training while using up to 10^6 for testing (~ 10^5 in semantickitti since it only has around 10^5 pts per frame). Our preprint will be updated in the next version.

Unfortunately, we haven't conducted ablation studies to evaluate how the number of input pts affects the final performance, but it's worthwhile to investigate it.

**Comment by tornadomeet** [comment]
@Yang7879  Thank you for your reply！
so in your figure7:
![figure7](https://user-images.githubusercontent.com/5860892/69837511-3019b780-128a-11ea-9ccc-83cfe4edd1f3.png)
does it mean that the value of N is  about 1e-5 during training?

and what the value of ```batch-size```?

**Comment by Yang7879** [comment]
Hi @tornadomeet , N is 50k as shown in Table 3 of the preprint. Batchsize is 6 in training and up to 20 in testing for the full utilization of a 2080Ti. They may be more or less if u use other GPUs.

**Comment by shuangjiexu** [comment]
Hi @Yang7879 , 

the infer time reported in the Fig.1 of paper is calculated by batch size 20 or by batch size 1?
a) batch size 1, total infer time = 0.04s;
b) batch size 20, total infer time = 0.8s, each one is 0.04s.

Thanks!

**Comment by Yang7879** [comment]
Hi @shuangjiexu, the time of all approaches in Fig 1 is the averaged time for each frame when the same 2080Ti  is fully used (ie, in our case it's b; in other methods, the batch size is different because of different memory consumption and the pre/post-processing is also counted).  For detail settings, please refer to Sec 4.2 where the total time of different approaches is reported.

**Comment by tornadomeet** [comment]
@Yang7879  got it, thanks!
