### ISSUE TITLE
Pre trained model and Inference 

### ISSUE THREAD

**Issue by abhigoku10** [QingyongHu/RandLA-Net#10]
@morpheus1820 @Yang7879 @QingyongHu  Hi thanks for opensourcing the source code , i have following queries 
1. Can you share the pre-trained model for semantic kitti dataset i want to check the output on the custom dataset 
2.how to obtain the list of classes predicted from the model from the inference code
3.can we get the location of the predicted objects or draw cuboids around them
THanks in advance

**Comment by QingyongHu** [comment]
Hi, @abhigoku10, thx for your interest in our work!
1. Please find the pre-trained model of SemanticKITTI dataset here, [https://www.dropbox.com/sh/vpn1ctxqjdj8qm8/AADTiCw81cfrRjEr52jkSbZMa?dl=0](url), download this to the code folder and then running the following command to test:
python main_SemanticKITTI.py --mode test --gpu 0
In addition, I would suggest to directly train our RandLA-Net on your custom dataset (if your data has been labeled).
Note that, please download the newest code, we have fixed some small bugs in the code.
2. For SemanticKITTI dataset, the output label should be:
{ 0: 'car', 1: 'bicycle', 2: 'motorcycle', 3: 'truck', 4: 'other-vehicle', 5: 'person', 6: 'bicyclist', 7: 'motorcyclist', 8: 'road', 9: 'parking', 10: 'sidewalk', 11: 'other-ground', 12: 'building', 13: 'fence', 14: 'vegetation', 15: 'trunk', 16: 'terrain', 17: 'pole', 18: 'traffic-sign'}
3. I would suggest you to use 3D object detection algrithom to direct obtain the bounding boxes of specific objects

**Comment by abhigoku10** [comment]
@QingyongHu  thanks for your response 
Q1. i have downloaded the model file shall test it on custom or other dataset . Unfortunately i donot have custom dataset annotated . R u aware of any open source dataset anntotation tool for annotating of semantic lables 
Q2 wokay i shall have a look into the output 
Q3. I was thinking about using output of from your model and giving it clustering methods to obtain the cuboid bounding boxes instead of going to 3D detection algorithms

**Comment by QingyongHu** [comment]
Hi, @abhigoku10, sorry for the late response.
Q1, have you tried this? https://github.com/jbehley/point_labeler
Q3, I haven't tried this before, but you are encouraged to have a try. Good Luck :)

**Comment by abhigoku10** [comment]
@QingyongHu  thanks for the response , i am having one more query . when i am trying to give a custom data / other dataset for inference with no labels i am facing the error ""main_SemanticKITTI.py", line 77, in spatially_regular_gen
    self.possibility[cloud_ind][selected_idx] += delta
IndexError: index 42094 is out of bounds for axis 0 with size 9111
[[{{node PyFunc}}]]
[[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. "  do you have any code which can be used to convert custom / other data into the required format

**Comment by QingyongHu** [comment]
@abhigoku10 This is mainly because your custom data does not have so many numbers of points as the data in SemanticKITTI. The point cloud in SemanticKITTI dataset at least has more than 81920 points for each scan. Therefore, we set num_points=~50K for each batch data.

Can you please have a look at the file utils/data_prepare_semantickitti.py? Hope it would be easy to follow. Also, you may need to change the num_points in helper_tool.py

**Comment by abhigoku10** [comment]
@QingyongHu  thanks for the pointers it was quite helpful , following this i have few queries . 
Q1. in the semantickitti.yaml file there is section "content: # as a ratio with the total number of points" should we modify these values for custom dataset 
Q2. For the semanttic kitti dataset along with x,y,z,r is the input to the module where r is the remission and intensity is both these params considered 
Q3. Is there any  thershold which we can varry to test the output on the custom dataset 
Q4. in the data_prepare_semanttickitti.py there is grid_sizer param should we vary it for custom data , if so in which condition should we varry it 
Thanks in advance

**Comment by QingyongHu** [comment]
Hi @abhigoku10, 

> Q1. in the semantickitti.yaml file there is section "content: # as a ratio with the total number of points" should we modify these values for custom dataset
-We don't use this in our code. 

> Q2. For the semanttic kitti dataset along with x,y,z,r is the input to the module where r is the remission and intensity is both these params considered
We do not consider remission in our code, but you are welcome to try this to see if it works.

> Q3. Is there any thershold which we can varry to test the output on the custom dataset
As you mentioned, maybe you need to consider the grid_size. Also, you are suggested to revise the code here.

> Q4. in the data_prepare_semanttickitti.py there is grid_sizer param should we vary it for custom data , if so in which condition should we varry it
This mainly depends on how many points left after the grid_subsampling operation. That is, mainly depends on the sparsity of the points in your custom data

**Comment by AnkyZhang** [comment]
Hi, @QingyongHu , Could please share the pre-trained model of S3DIS dataset? And  I want to test other .ply files on the model, could you please tell me the way to test a .ply file? Thanks a lot !

**Comment by QingyongHu** [comment]
@AnkyZhang I would suggest you train the model by yourself, as we use 6-fold cross-validation on the S3DIS dataset, so there will be 6 models in total. I do not quite understand what you want to do, you mean evaluate our RandLA-Net on your custom dataset?

**Comment by AnkyZhang** [comment]
@QingyongHu , Thanks for your reply.  : ）Actually,  I have been training on S3DIS, and it seems going to take me several gpu-days for each area. How about your time efficiency when training？（I wonder that there is something wrong in my steps.） 
And actually , I want to evaluate your RandLA-Net on our custom dataset. And I wonder if I can take the whole data as the input for RandLA-Net directly (instead of split the data into some blocks).

**Comment by QingyongHu** [comment]
@AnkyZhang We have trained the model on an NVIDIA RTX2080Ti GPU and an AMD3700X CPU, it takes like 3 hours to converge (It is not necessary to train 100 epochs). I am not sure what kind of hardware you are using, maybe that's the problem.

Our model is able to be scaled to large-scale point clouds, we have tried to train on 40960 points but tested on 1000000 points, the results seem to have very minor differences. Therefore, you are encouraged to try our model on your custom dataset.

**Comment by AnkyZhang** [comment]
It's really helpful and thanks a lot!

**Comment by KangchengLiu** [comment]
Please provide 6-fold models on the S3DIS dataset, because we have no access to GPU due to Ncov-2019.

**Comment by abhigoku10** [comment]
@QingyongHu  hi i am getting this following error when i am doing inference 
 proj_inds = np.squeeze(search_tree.query(points, return_distance=False))
  File "sklearn/neighbors/binary_tree.pxi", line 1303, in sklearn.neighbors.kd_tree.BinaryTree.query

lib/python3.5/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')

raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64

Please let me knw hwo to solve it

**Comment by QingyongHu** [comment]
Hi @abhigoku10, can you please check if you have already correctly built the search_tree?

**Comment by gxd1994** [comment]
HI @QingyongHu @abhigoku10 @AnkyZhang  can you uploading a model to Google driver ? I Can't download the data in dropbox due to network reasons

**Comment by abhigoku10** [comment]
@QingyongHu  now i am able to run the inference . i did an experiment where i reduced the point cloud density by 90% from the orginal during which the output is degrading with misclassification , can you please share your thought in this since in custom dataset the total points i am having is around 3000 in frontal view . is there any impact on the density of points if so how to tactal it 
@gxd1994  please share your dropbox link i shall upload it there

**Comment by gxd1994** [comment]
@abhigoku10  https://www.dropbox.com/sh/vpn1ctxqjdj8qm8/AADTiCw81cfrRjEr52jkSbZMa?dl=0
thx you!

**Comment by QingyongHu** [comment]
@gxd1994, We have updated the code and provided the pre-trained models and dataset results [here](https://drive.google.com/drive/folders/1iU8yviO3TP87-IexBXsu13g6NklwEkXB).

**Comment by QingyongHu** [comment]
Hi @abhigoku10, If I understand correctly, you mean the model is trained using the point cloud data from the SemanticKITTI dataset, but inference on a point cloud with much less density? If so, the overall performance is likely to decrease as the data distribution is indeed different. 

I would suggest you train on your custom dataset or finetuning on the pre-trained model, so that the model is more likely to generalize to the new dataset.

**Comment by abhigoku10** [comment]
@QingyongHu  yup u have understood it clearly.. thanks for the suggestion even i was thinking the same but should i train from scratch or should i do transfer learning .. should i maintain the default training params

**Comment by QingyongHu** [comment]
@abhigoku10, I would suggest you try training on your own data first if you have sufficient data (~5 million points). Otherwise, I would suggest you using the pre-trained model and fine-tune on your own dataset (better to freeze the parameters defined in the feature extraction module).

**Comment by KangchengLiu** [comment]
The pretrained results of S3DIS can not get 68.4 MIOU, please check with the pretrained results.

**Comment by QingyongHu** [comment]
Hi @KangchengLiu. Please download the results from Google drive and run the `6_fold_cv.py`:
![image](https://user-images.githubusercontent.com/29670234/77930606-0063d600-72a3-11ea-963e-7f1cb6de9c2a.png)

**Comment by KangchengLiu** [comment]
I got the same result when I changed "#labels = original_data['class']" to "labels = pred_data['label']".
![Screenshot from 2020-03-31 00-08-37](https://user-images.githubusercontent.com/37166840/77935291-d4b51000-72e3-11ea-806a-169697a09a4e.png)

![Screenshot from 2020-03-31 00-05-55](https://user-images.githubusercontent.com/37166840/77934993-6cfec500-72e3-11ea-8e7f-5ab70aa54e8b.png)

But when I use "#labels = original_data['class']", the mIOU is lower. pls explain, thanks!

**Comment by QingyongHu** [comment]
I have double-checked the results on my pc, the two results are the same, please check your own data and the data preparation to make sure it is correct.

![image](https://user-images.githubusercontent.com/29670234/77939297-dca68d00-72ae-11ea-801d-4846721d6405.png)

**Comment by abhigoku10** [comment]
@QingyongHu thanks for the suggestion earlier , i have trained on my custom dataset with 2k frames for only class objects like car, peds,truck and there remaining points i have grouped to unlabelled dataset. below are the observations 
1.when i kept it for training for the 10th epoch i have obtained the model after which i kept on getting "nan" error 
2.when i tested with the 10th epoch model even the roads trees classes are getting detected as car/truck
Can you share your experience on this

**Comment by honggesmile** [comment]
> Hi, @QingyongHu , Could please share the pre-trained model of S3DIS dataset? And I want to test other .ply files on the model, could you please tell me the way to test a .ply file? Thanks a lot !

Have you solved this problem, that is, you have trained the model, and then how to predict your own ply file (input the ply point cloud and output the segmented result)，thank you for your reply

**Comment by QingyongHu** [comment]
Hi @abhigoku10, 
For the first question, it is better to add a very small value at the end to avoid dividing by 0
true_positive_classes[n] / float(gt_classes[n] + positive_classes[n] - true_positive_classes[n]+1e-6)

For the second question, please check if the input to the loss function is correct
> Expected size[0] in [0, 0], but got 1
> [[node loss/softmax_cross_entropy_with_logits_sg/Slice (defined at /RandLA-Net-master_val/RandLANet.py:265) ]]

> 2.when i tested with the 10th epoch model even the roads trees classes are getting detected as car/truck
This is because the network will not count the loss of unlabeled points during training, which means that we do not consider unlabeled as a meaningful semantic category, therefore the network tends to predict them as a meaningful semantic category. As you mentioned, you did not label the road and tree class, so the roads trees classes are getting detected as car/truck

**Comment by abhigoku10** [comment]
@QingyongHu thanks for the response , you have trained the model on 19 classes if i should train the model only 6 classes what is the changes to be in the source code

**Comment by KiranAkadas** [comment]
@abhigoku10 Have you changed the shape of weights in helper_tool.py?

**Comment by abhigoku10** [comment]
@QingyongHu @KiranAkadas hi thanks for the response , i reduced the number of classes in the semattic kitti from 19 to 6 and changed the num_classes,learning_rate params , rest remained the same . should i change some other params ??with a little debugging i came across this param " num_points = 4096 * 11 " should i varry this param if i reduce the number of of class or reduce the point clouds can you explain a bit more

**Comment by KiranAkadas** [comment]
In my case, I changed the num_Classes and the the number of weights in the following line:

https://github.com/QingyongHu/RandLA-Net/blob/3c5421d7e1dae0440455f9d1046d86afbdbd295a/helper_tool.py#L256

There are 19 here, you need only 6, so you can remove the other 13.

**Comment by abhigoku10** [comment]
@KiranAkadas  thanks for pointers , exactly what does this num_per_class weights signify

**Comment by KiranAkadas** [comment]
Those are the number of points I suppose in each category

**Comment by QingyongHu** [comment]
Hi @abhigoku10, can you please make your questions more clear?

**Comment by abhigoku10** [comment]
@QingyongHu hi i am going to elaborate the question
Q1. i took semanttic kitti dataset and reduced the num_class in  helper_tool.py and tried to train the model , but i am getting the nan error , so wanted to knw if there is any other params which i need to change before training ??

**Comment by QingyongHu** [comment]
Hi @abhigoku10, 
First, please make sure the label values in your data is starting from zero, for example, if you have 6 class, the label value in your data should be 0-6. if not, please map the label values to this order. Otherwise, the loss functions make no sense.
Second, check if you want to ignore the class '0' or not, if yes, just follow the code in SemanticKITTI, if not, please revise this [line](https://github.com/QingyongHu/RandLA-Net/blob/6da2ff60c94233c8754d2e04aba3eda3c4fde360/main_Semantic3D.py#L29) as:         self.ignored_labels = np.array([])

**Comment by abhigoku10** [comment]
@QingyongHu i have double checked this yet i m running into the same error which i have mentioned above is there any way to debug

**Comment by QingyongHu** [comment]
Hi @abhigoku10, 
My suggestions are:
1. Please check the label values after you have done all the data processing. if you use 8 classes, the label value should range from 0-7.
2. Please modified [here](https://github.com/QingyongHu/RandLA-Net/blob/6da2ff60c94233c8754d2e04aba3eda3c4fde360/main_SemanticKITTI.py#L16-L35).
3. You can also try to set a small initial learning_rate

**Comment by abhigoku10** [comment]
@QingyongHu thanks for response , i have done the following 1 and 2 mentioned and when i done more debug i am seeing that the Lout is giving nan value , PFA image 
![image](https://user-images.githubusercontent.com/22094053/79219726-6b4f0880-7e70-11ea-8bbe-e1fe5e85ceb0.png)

if you observe for Epoch 2 in step 2250 i get Lout and Acc as nan afte that i get caught nan error even in step 1150 of Epoch 1 i get Lout and Acc = nan 
I have printed the loss values of the classes also and get nan at the last class

**Comment by QingyongHu** [comment]
Hi @abhigoku10. This is most likely caused by the data, I would suggest you write a code to traverse all the processed data and check the labels.
For the [mIoU calculation](https://github.com/QingyongHu/RandLA-Net/blob/6da2ff60c94233c8754d2e04aba3eda3c4fde360/RandLANet.py#L243), you should add a very small value at the end in case of divide by 0

**Comment by abhigoku10** [comment]
@QingyongHu @KiranAkadas  thanks for your support i was able to solve the training issue which i was facing . 
@QingyongHu what is the impact if i ignore class 0 while training , since loss wont be obtained for the class 0, so during inference if the scene has other classes will it segmented as one of the trained class ??

**Comment by QingyongHu** [comment]
@abhigoku10 The reason we ignore class 0 in Semantic3D and SemanticKITTI is that, this class has no semantic meaning at all, so it is meaningless to predict a point belongs to this class during inference. Therefore, the network will only predict if the points belong to these meaningful semantic classes.

I haven’t tried this, but my intuition is that this unlikely to work. First of all, the point clouds in these two datasets are acquired from different sensors. The data is very different and the density also varies. I would not suggest you do this as this doesn't make any sense in practice.

**Comment by abhigoku10** [comment]
@QingyongHu thanks for the response , I had trained the model by considering only 6 classes and the remaining as unlabelled class data and obtained the model but when i did the inference  all the points were getting predicted as one of the 6 class Eg tree was also getting predicted car also . THen i trained the model considering 6 classes and the remaining class as 7 class instead of unlabelled class now we r getting results .. Any comments on this

**Comment by QingyongHu** [comment]
Hi @abhigoku10.
First, I am not sure if there is a problem with your implementation.
In addition, for the first question, this is likely to happen if the data are extremely unbalanced. For example, the number of points belongs to cars is 1000 times than other categories.

**Comment by sxsong1207** [comment]
@QingyongHu Hi, thanks for your great work! I am looking forward to test your network with pretrained model, but unfortunately, the dropbox link is out of date, could you update it? It will be very appreciated! Thank you advance!

**Comment by sandeepnmenon** [comment]
> @QingyongHu Hi, thanks for your great work! I am looking forward to test your network with pretrained model, but unfortunately, the dropbox link is out of date, could you update it? It will be very appreciated! Thank you advance!

+1
I see the GDrive link from the readme : https://drive.google.com/drive/folders/1vVa1uCK__2JRj2kj94TjcngwEyh9JSon
Is this model trained on SemanticKITTI? (It is only 14MB)

**Comment by swzaaaaaaa** [comment]
> Hi @KangchengLiu. Please download the results from Google drive and run the `6_fold_cv.py`:
> ![image](https://user-images.githubusercontent.com/29670234/77930606-0063d600-72a3-11ea-963e-7f1cb6de9c2a.png)

![image](https://user-images.githubusercontent.com/43643616/124343782-d5340900-dc00-11eb-9f83-e612b6d3db00.png)
Hello, I used the result of SD3ID you provided, then python 6_fold_cv.py,but i get something like this?

**Comment by swzaaaaaaa** [comment]
> I got the same result when I changed `labels = original_data['class']` to `labels = pred_data['label']` in `6_fold_cv.py` as shown below.
> ![Screenshot from 2020-03-31 00-08-37](https://user-images.githubusercontent.com/37166840/77935291-d4b51000-72e3-11ea-806a-169697a09a4e.png)
> 
> ![Screenshot from 2020-03-31 00-05-55](https://user-images.githubusercontent.com/37166840/77934993-6cfec500-72e3-11ea-8e7f-5ab70aa54e8b.png)
> 
> But when I use `#labels = original_data['class']`, the mIOU is lower. Pls explain, thanks!

请问，这个问题解决了吗？

**Comment by swzaaaaaaa** [comment]
> Hi @KangchengLiu. Please download the results from Google drive and run the `6_fold_cv.py`:
> ![image](https://user-images.githubusercontent.com/29670234/77930606-0063d600-72a3-11ea-963e-7f1cb6de9c2a.png)
![image](https://user-images.githubusercontent.com/43643616/124344458-d5ce9e80-dc04-11eb-94e3-725f0160f03b.png)

Hello, I used the result of SD3ID you provided, then python 6_fold_cv.py,but i get something like this?

**Comment by shaofeifei11** [comment]
> thanks for your support i was able to solve the training issue which i was facing

`Round 1 | epoch=4 | Step 00000075 L_out=10.392 Acc=0.29 ---731325.27 ms/batch
Round 1 | epoch=4 | Step 00000076 L_out=7.812 Acc=0.48 ---742044.44 ms/batch
Traceback (most recent call last):
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected size[0] in [0, 0], but got 1
	 [[{{node loss/softmax_cross_entropy_with_logits_sg/Slice}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sff_create_baseline.py", line 60, in <module>
    best_miou, best_OA = model.train(round_num=round_num)
  File "/home/shaofeifei/workspace/activatelearning_pointcloud/randlanet-superpoint_semantic3d_s3dis/RandLANet.py", line 277, in train
    _, _, summary, l_out, probs, labels, acti, acc = self.sess.run(ops, feed_dict=self.get_feed_dict(dat, True))
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected size[0] in [0, 0], but got 1
	 [[node loss/softmax_cross_entropy_with_logits_sg/Slice (defined at /home/shaofeifei/workspace/activatelearning_pointcloud/randlanet-superpoint_semantic3d_s3dis/RandLANet.py:618) ]]

Caused by op 'loss/softmax_cross_entropy_with_logits_sg/Slice', defined at:
  File "sff_create_baseline.py", line 59, in <module>
    model = Network(cfg, dataset_name, sampler_args, test_area_idx, reg_strength=reg_strength)
  File "/home/shaofeifei/workspace/activatelearning_pointcloud/randlanet-superpoint_semantic3d_s3dis/RandLANet.py", line 83, in __init__
    self.loss = self.get_loss(valid_logits, valid_pseudo, valid_activation, self.class_weights)
  File "/home/shaofeifei/workspace/activatelearning_pointcloud/randlanet-superpoint_semantic3d_s3dis/RandLANet.py", line 618, in get_loss
    unweighted_losses = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=one_hot_labels)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2561, in softmax_cross_entropy_with_logits
    labels=labels, logits=logits, axis=dim, name=name)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2370, in softmax_cross_entropy_with_logits_v2
    labels=labels, logits=logits, axis=axis, name=name)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2464, in softmax_cross_entropy_with_logits_v2_helper
    precise_logits = _flatten_outer_dims(precise_logits)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2095, in _flatten_outer_dims
    array_ops.shape(logits), [math_ops.subtract(rank, 1)], [1])
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 707, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8236, in _slice
    "Slice", input=input, begin=begin, size=size, name=name)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/shaofeifei/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Expected size[0] in [0, 0], but got 1
	 [[node loss/softmax_cross_entropy_with_logits_sg/Slice (defined at /home/shaofeifei/workspace/activatelearning_pointcloud/randlanet-superpoint_semantic3d_s3dis/RandLANet.py:618) ]]
`

I also sufferr from this issue. Could you tell how to sovle it?
