### ISSUE TITLE
why there is OutOfRangeError in Tester

### ISSUE THREAD

**Issue by hansen7** [QingyongHu/RandLA-Net#96]
Hi, Qingyong. I really like your work, and with more digging into the tester code, I noticed that there is a `try`, `exception` syntax in all three testers, can you help me understand why sometime there will be `tf.errors.OutOfRangeError`?

https://github.com/QingyongHu/RandLA-Net/blob/3aafa161f32730fa1a9bbd63d06afe8e18ce9ab9/tester_SemanticKITTI.py#L91-L93

**Comment by hansen7** [comment]
figure it out :)

**Comment by youssef962** [comment]
I'm facing the same problem, please can you tell me why this error is generated?
@hansen7

**Comment by hansen7** [comment]
it is not an error, just because the prediction of all the pooints are not ready so it requires further looping

**Comment by youssef962** [comment]
@hansen7 
Thanks a lot for your quick reply. I guess it's an error as it breaks with me (check my issue #207). All what I did is trying to test a data with dummy ground truth class label in order to give  the data the required shape the code asks, but after 100 steps it broke and gave me the error in the issue. So please if you know what's wrong or how to test unlabeled data please tell me how. Thanks in advance.
